<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PP.Domain\PP.Domain.csproj" />
    <ProjectReference Include="..\PP.Infrastructure\PP.Infrastructure.csproj" />
  </ItemGroup>

</Project>
